# -----------------------------------
# ANALYSIS AGGREGATOR
# -----------------------------------

# Purpose:
# Combine AI analysis results from
# multiple log chunks into one
# consolidated report.

# Future Enhancements:
# - Deduplicate repeated findings
# - Merge recurring errors
# - Severity aggregation
# - Incident timeline generation
# - Executive summaries

def combine_chunk_results(results):

    combined_sections = []

    for result in results:

        chunk_number = result["chunk_number"]

        chunk_analysis = result["analysis"]

        section = f"""
## Chunk {chunk_number} Analysis

{chunk_analysis}
"""

        combined_sections.append(section)

    final_report = "\n\n".join(combined_sections)

    return f"""
# Consolidated AI Log Analysis Report

The following report was generated by analyzing
multiple log chunks independently.

---

{final_report}
"""