def generate_markdown_report(
    final_result,
    metrics,
    chunk_count
):

    report = f"""
# AI Incident Analysis Report

## Analysis Metadata

- Total Lines: {metrics["total_lines"]}
- Total Characters: {metrics["total_characters"]}
- Important Errors: {metrics["important_error_count"]}
- Stack Traces: {metrics["stack_trace_count"]}
- Chunks Processed: {chunk_count}

---

{final_result}

---

Generated by AI Log Analyzer
"""

    return report


def generate_text_report(
    final_result,
    metrics,
    chunk_count
):

    report = f"""
AI INCIDENT ANALYSIS REPORT

====================================

Total Lines:
{metrics["total_lines"]}

Total Characters:
{metrics["total_characters"]}

Important Errors:
{metrics["important_error_count"]}

Stack Traces:
{metrics["stack_trace_count"]}

Chunks Processed:
{chunk_count}

====================================

{final_result}

====================================

Generated by AI Log Analyzer
"""

    return report